title:            雪底藏松
description:      雪底藏松的blog
disqus_shortname: minfeizhou
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:
baseurl: "/"

# Owner/author information
# owner:
#   name:           雪底藏松
#   avatar:         main.jpg
#   bio:            "传说中的个人简介"
#   email:          chisifang@163.com
#   # Social networking links used in footer. Update and remove as you like.
#   twitter:
#   facebook:
#   github: MinfeiZhou
#   stackexchange:
#   linkedin:
#   instagram:
#   flickr:
#   tumblr:
#   weibo: http://weibo.com/zmf1990/home
#   # google plus id, include the '+', eg +mmistakes
#   google_plus:

# --- Navigation bar options - start --- #
# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
avatar: "/images/tx.jpg"

# List of links in the navigation bar
navbar-links:
  首页: ""
  所有文章: "posts"
  文章类别: "tags"
  关于我: "about"
# --- Navigation bar options - end --- #

# Background image to be tiled on all pages
background: ricepaper.png

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Chongqing
future:      true
highlighter: pygments
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 3

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
